### PR TITLE
Update CONTRIBUTING v2.md

### PR DESCRIPTION
**Pull request by AsamDiegoSanchez**
second iteration to improve the contribution guidelines

### CODE REVIEW

**Comment by ThomasMatthesASAM** [comment]
## Review findings

In the first headline `Contributing to ASAM e.V open-source Projects`:
- the dot after `ASAM e.V.` is missing

**Comment by ThomasMatthesASAM** [comment]
I was not familiar with the abbreviation `IP` in `All IP remains that of the original contributors...`, perhaps it would be better to use the full form `intellectual property`.

**Comment by ThomasMatthesASAM** [comment]
I am unsure whether we should also refer our actual `Antitrust Reminder` next to the `Project Guide` reference in section `Asking Questions`.
Could be an additional safeguard on our part, but it is not clear to me whether this is necessary in context of this Contribution Guideline.
If you want to add this after checking, here is the link:
- https://www.asam.net/index.php?eID=dumpFile&t=f&f=2496&token=90723c0e1dd4dc7000dd1bd362597c043ce9ecaf

**Comment by ThomasMatthesASAM** [comment]
`(described more fully later in this document)` maybe its better to link the correct section here:
- `(described more fully in section [REFERENCE])`

**Comment by ThomasMatthesASAM** [comment]
Can the single quote at the end of `with this project or the open source license(s) involved.'` removed?

**Comment by ThomasMatthesASAM** [comment]
It may be worth considering adding a comment to the pull request message(?):
- `Signed-off-by: Firstname Lastname <email@address.com> <comment>`

**Comment by ThomasMatthesASAM** [comment]
I think `unixoid` is a german term for operating systems similar to Linux. According to Wikipedia, the English translation for this is `Unix-like`.

**Comment by ThomasMatthesASAM** [comment]
It might also be helpful to be able to formulate a question, if this is provided: `The first step is to identify and describe a bug, feature or question`.

**Comment by ThomasMatthesASAM** [comment]
Use the escape sequence (`` ` ``) for highlighting the backtick, near `Especially put code blocks and console outputs in backticks (```)`, if the intention was to display a single backtick.

**Comment by ThomasMatthesASAM** [comment]
A backward link for `Follow the signing instructions for commits (DCO) above` is suitable:
- `Follow the signing instructions for commits described in section [REFERENCE]`

**Comment by ThomasMatthesASAM** [comment]
Ambiguity in section `Writing Commit Messages`:
- `subject`
- `subject line`
- `short summary`

My suggestion is to use only one expression of these.

**Comment by ThomasMatthesASAM** [comment]
### Open questions:

Do the following templates already exist, if so where can they be found?
- `... Fully complete the provided issue template. ...`
- `... template for pull requests ...`

**Comment by AsamDiegoSanchez** [comment]
@ThomasMatthesASAM thank you very much, I´ve added most of the suggestions and changes.

**Pull request merged**
